digidem/mapeo-desktop

package.json
server.js

Replicate to hyperlog instead of osmdb

---

bin/build_id_editor.js

Setting the version needs to happen at build time, since it requires knowledge
of the build-time package.json file's version string. In the future it'd be
nice to have a separate static compilation step (maybe using @substack's
`static-module`, or just plain `browserify`), but this is quick and dirty and
gets the job done.

Monkey patch version at build-time.

---

browser/main.js
lib/user-config.js
server.js

This adds a new user settings file, 'metadata.json'. It contains a "dataset_id" field to identify the dataset that the user would like to limit synchronization to.

Add dataset_id to the user settings

---

app.js
browser/main.js
lib/user-config.js
server.js

Use dataset_id to filter sync files (replaces #51)

---

app.js
browser/sync_usb.js

This reports the error in an Electron message dialog, and then
terminates the process with a non-zero exit status.
Addresses #22.

Catch node process exceptions and exit gracefully.

---

app.js
browser/main.js
lib/menu.js
package.json

Addresses #32.
Enables a "Zoom to Data" menu item under the "Visualicion" submenu, which
locates the general location of the dataset and pans + zooms the map viewport
there.

"Zoom to Data" feature.

---

app.js
browser/main.js

Fixes https://github.com/digidem/mapeo-desktop/issues/33

Refresh iD view when settings are updated.

---

lib/polygon-feature.js
lib/preset-matcher.js
server.js

- Uses iD’s polygon detection algorithm based on custom presets.
- Injects preset icons and ids into exported geojson
- Replaces ‘:’ with ‘_’ for legacy data/tag names

GeoJSON export polygon detection + preset injection

---

app.js
browser/welcome.js
package.json

copy example file first before syncing

---

app.js
browser/generating_indexes.html
browser/generating_indexes.js
browser/latlon_dialog.html
browser/latlon_dialog.js
browser/main.js
id_monkey_patches/id-ui-latlon-display.js
lib/locale.js
lib/menu.js
locales/en.json
locales/es.json

At last! Paste in a `latitude, longitude` and have Mapeo zoom there. Combined with https://github.com/digidem/mapeo-desktop/pull/104 this makes it much easier to share locations and find them again.

Add dialog to enter a lat/lon value & zoom there

---

app.js
lib/osm-stats.js
package.json

This adds a "stats" index that tracks a rolling average latitude and longitude
of all nodes in the dataset, and modifies "Zoom to Data" to move to that mean
location.

Improve 'Zoom to Data' feature

---

locales/en.json
locales/es.json

Figured out that if putting it in order Latitude, Longitude it was zooming to the side of Antarctica instead of Puto Mayo

incorrect lat/lon order when asking for coordinates

---

src/api.js
src/components/SyncView.js

depends upon mapeo-server bump

unannounce when syncview component closes

---

index.js
package-lock.json
package.json
src/server.js

Can override mapfilter styles by importing your custom style into the `userData/styles/<stylename>` directory

Use custom style in mapfilter

---

index.js

Unpacking styles should not crash the app if it fails. We need to fix how styles are done on mapeo-desktop and implement the custom style frontend soon, right now this is a hack

Unpack styles fix

---

index.js
src/components/MapEditor.js
src/lib/tile-importer.js
src/tile-server.js

Also, expand the tile server's knowledge of other things besides just png

fix some bugs with offline tiles

---

src/renderer/components/MapFilter.js

fixes #211
are there any other properties that shouldn't be updated?
wondering also if this should be handled in mapeo-core instead @gmaclennan

fix(mapfilter): make sure certain props shouldn't update

---

docs/testing.md

Minor correction added during a quick proof reading of this testing doc.

Added a space for better readability

---

docs/offline_tiles.md

Minor Typo in parameters corrected

---

src/main/window-state.js

fix: sometimes the app would fail to load on Windows

---

.github/workflows/nodejs.yml
bin/release_latest.js
package.json

chore: Separate Windows 32bit builds

---

src/main/mapeo.js

fix: only ever call close once, fixes #331

---

index.js
package-lock.json
package.json
src/background/mapeo-ipc.js
src/background/mapeo.js
src/background/server.js
src/main/ipc.js
src/main/menu.js
src/main/user-config.js
src/renderer/components/SyncView/SyncAppBar.js
src/renderer/components/SyncView/SyncFooter.js
src/renderer/components/SyncView/index.js
src/renderer/new-api.js

This was a rabbit hole of rabbit holes, but finally got it to work well today.
[Demo video.
](https://www.dropbox.com/s/ml9773ib8zo0o8o/project-key.mp4?dl=0)
I haven't yet tested it with the mobile app, but I did test it with my test device emulator.
Fixes #339 #327

fix: Import Configuration... should work without restarting Mapeo

---

package-lock.json
package.json

fix: Multiselect field should not error if has select_one data

---

package-lock.json
package.json
src/renderer/components/MapEditor/index.js
src/renderer/new-api.js

fix: update to electron 9.1.2

---

src/main/ipc.js
src/main/menu.js
src/renderer/components/MapEditor/ExportButton.js
src/renderer/components/MapEditor/index.js
src/renderer/components/MapFilter/DataExportDialog.js
src/renderer/components/MapFilter/MapExportDialog.js
src/renderer/components/SyncView/index.js

Electron dialogs are now promise based so all of our dialog code broke!

fix: Ensure all dialogs will work with Electron 9

---

src/renderer/components/SyncView/SyncFooter.js
src/renderer/new-api.js

Avoid displaying full secret key on the synchronize UI. Fix #414 . 
Tested on MacOS 10.14.6.
I agree with #414 that displaying other configuration names and versions would be preferable and helps user diagnose their issues. Any suggestion on what should also be displayed?

fix: only display the first 5 character of the project secret key

---

.storybook/__mocks__/electron.js
src/renderer/components/MapFilter/ReportView/PDFReport.stories.js

Storybook was failing to run; this fixes two issues that were causing it to fail to load.

chore(test): add proper mocks to storybook

---

.github/workflows/nodejs.yml
src/background/mapeo-core/mapeo.js
src/background/mapeo-core/osm-stats.js
src/main/menu.js
src/renderer/components/MapEditor/index.js

Fixes most of #474 apart from considering edits. E.g. if you edit a point 3 times, that will be counted as 3 points. This should still work "well enough" to find your data.

fix: Fix "zoom to data": include deletions & correct density calc

---

package-lock.json
package.json

feat: Update iD Editor background imagery (fix mapbox satellite)

---

messages/main/en.json
messages/renderer/en.json
src/renderer/components/MapEditor/ExportButton.js

fix: Update import/export labels for territory data

---

src/main/auto-updater.js

Fixes #499 and #500
Notes:
- there's a slight error in string concatenation logic because JS is fun like that

fix: fix built url in autoupdater

---

builder.config.js

Waiting on new windows cert to unblock failing CI, so just need to build the assets in CI here so that programs can QA 5.4.0-beta.16

chore: Disable windows signing temporarily

---

package-lock.json
package.json

fix: Upgrade mapeo-server to fix syncfile close issue

---

messages/main/en.json
package-lock.json
src/main/menu.js

Adds a confirmation dialog when a config has been successfully imported.

chore: Added confirmation dialog for config import.

---

.github/workflows/nodejs.yml

chore: Use macos-11 image for CI

---

package-lock.json
package.json

Upgrades to v3.6.1 which includes a patch to fix missing/stale translations

chore(deps): Update mapeo-default-settings to latest

---

README.md

This is a quick PR just replacing the outdated ` Community` links with Discord.

chore: Add Discord link to README.MD

---

package-lock.json
package.json

chore(deps): update mapeo-config-icca 1.7.1

---

.github/workflows/nodejs.yml

Update the github workflow to:
- fail fast
- increases attempts from 1 to 5

chore: update github workflow

---

docs/CONTRIBUTING.md

Corrected a minor typo in section heading

Minor typo 'Debbugging'
