digidem/mapeo-desktop

- bin/build_id_editor.js
- package.json
npm can install packages into places other than `../node_modules`, so this patch makes these work more reliably under different scenarios
> resolve paths using require.resolve() and require() instead of ../node_modules

- bin/build_id_editor.js
- id_monkey_patches/no-slow.js
This hack monkey patches around the setTimeout() that mainline OSM needs because of write throttling, but we don't need anything of the sort. This should speed up editing.
> remove timeouts for faster editing

- browser/sync.js
- server.js
With this hack, the replication UI waits 5 seconds for the hyperlog replication to kick off its add/preadd phase. I haven't figured out how to fix this properly, but this hack seems to work in the meantime.
Make *sure* that dependent modules are using hyperlog-index 4.0.1 or 5.0.1, not 4.0.0 nor 5.0.0! With those upstream fixes, the replication doesn't get permanently hung in the non-ready state.
> hacky way to have the replication UI report properly

- .travis.yml
- README.md
- appveyor.yml
- bin/create_installer.js
- bin/create_macos_dmg.js
- bin/create_windows_installer.js
- bin/package_macos.js
- bin/package_windows.js
- package.json
The deployment workflow for this configuration is as follows,
1. Tag a new version (e.g. 'npm version patch')
2. Push to the Github repo (e.g. 'git push origin master')
From here, Appveyor will pick up the tag, build the release and create a
new GitHub Release with the binary asset attached.
---
> Deploy tagged Windows/macOS builds to GitHub Releases (WIP)

- bin/create_macos_dmg.js
- bin/create_windows_installer.js
Windows: `Installar_Mapeo_vX.Y.Z_Windows.exe`
macOS: `Installar_Mapeo_vX.Y.Z_macOS.dmg`
> Add OS-specific suffix to installer filenames.

- bin/package_macos.js
- bin/package_windows.js
`version` is for the **Electron** version, not the app version.
> Use electron@1.3.4 for Win/Mac packaging, too.

- app.js
- browser/sync.js
- package.json
- replicate.html
- server.js
This modifies the sync logic to use hyperlog-sneakernet-replicator,
which performs hyperlog replication between a log and a single gzipped
tarball.
In terms of the sync user interface, this meant adding an additional
button ('Create File'), to differentiate between selecting an existing
.mapeodata to sync to, and creating a new one. One dialog would be
ideal, but Electron doesn't offer a nice Dialog API for this.
> Use single file tar.gz sneakernet replication.

- server.js
I got the impression from @gmaclennan and @substack that the underlying hyperlog issues that necessitated this hack have since been fixed.
My thinking here was that the delay hack (https://github.com/digidem/mapeo-desktop/commit/8ac48490317c56bedd4897b91d41fc5ea914ac18) was written on Mar 16, and [this bugfix on hyperlog events](https://github.com/mafintosh/hyperlog/pull/19) was submitted on Apr 11. Was that PR to address this issue, @substack?
If not, I'd be interested in hearing more about the kinds of case where you two noticed the indexer's `ready` failing to fire. Thanks!
> Remove 5000ms delay on post-sync indexing.

- lib/log.js
- package.json
This adds a small logging module to mapeo-desktop. It provides the following:
1. Both: A consistent `Console`-compatible interface for use in the node and
browser processes.
2. Node: logs to a text file in the user's electron application directory with
a unqiue timestamped filename.
2. Node: writes to both stdout and the log file.
3. Node: runs a tiny websocket server for browser communication.
4. Browser: connects to the node process' websocket server. (I could've used
ipc, but this will work across many windows without configuration.)
5. Browser: writes to both the websocket server and the browser's equivalent of
stdout.
6. Browser: captures browser errors and logs them.
All that's left is for us to start using the logging module in the codebase. Use is as simple as
```js
// node
var …
```
> Electron logging

- bin/build_id_editor.js
- id_monkey_patches/id-ui-latlon-display.js
Adds a label to the bottom right-hand corner that shows the viewport's current latitude and longitude. It replaces some iD-specific icons for bug reports and translations that aren't applicable for Mapeo.
There is right-hand zero padding so that the length of the element isn't constantly changing and creating visual noise.
Bonus: it's a text element, so you can easily select, copy, and paste it! :tada:
I'm especially interested in feedback on how I've monkey patched this in, and if anyone can think of a nicer way of doing this with less code duplication.
> Add a live "latitude,longitude" label

- index.js
- locales/en.json
- locales/es.json
- package.json
- src/components/Home.js
- src/components/MapFilter.js
- src/components/MenuItems.js
- src/components/Sidebar.js
- src/components/SyncView.js
- src/components/Welcome.js
- src/lib/export-data.js
- src/menu.js
- static/css/base.css
depends upon https://github.com/digidem/react-mapfilter/pull/94
tiny TODOs left:
This makes the menus a bit easier to understand and more symmetrical in both map editor and mapfilter mode.
MapEditor now has two export options in the menu (`geojson` and `shapefile`) while in mapfilter mode we have `csv` and `geojson`.
Now, there's only one Mapfilter menu instead of two and it has the ability to sync and see the MapEditor screen
> Custom menu items

- index.js
- src/lib/osm-stats.js
Creates a new version of the "osm stats" index that builds a low resolution density map of all nodes. When zooming to data, the tile with the highest density is used.
> feat(zoom-to-data): use a low-rez node density tilemap

- src/api.js
- src/components/SyncView.js
- static/css/base.css
This PR brings us one step closer to @aldopuicon 's ideal sync interaction.
* While sync is in progress, there are no buttons. 
* A sync that is currently in progress cannot be cancelled, yet. I wrote in capability to 'stop' the target in the server api, but the UI doesn't expose it yet. I figured this was a new feature and should be integrated on a feature branch separate from this one.
* Only one target is displayed while sync is in progress or complete. If you want to sync again, you need to hit 'ok' and re-open the sync screen.
> Prevent double sync

- src/components/SyncView.js
Ideally this would instead change on progress and report accurate progress events, but we need to first report the progress via the server somehow, where the sync is happening.
> fix: use a circular progress spinner that moves during sync

- src/components/MapEditor.js
this wasn't really creating any issues, but will keep the DOM from stacking up unnecessary divs
> only append customDefs when it doesn't already exist

- index.js
This PR proposes adding a logo to the [`BrowserWindow`](https://electronjs.org/docs/api/browser-window#new-browserwindowoptions). I am not sure about Win/Mac platform, but at least on Linux platforms there will be a nice logo showing in the taskbar.
Before:
After:
> Added logo to browser window

- src/components/MapEditor.js
Bug: in some cases points would not appear in MapEditor view
Reproduce:
1. Create some points in Map Editor (or alternatively, have some points ready)
2. Open Map Filter
3. Open Map Editor again. Points have disappeared.
4. Refresh/restart Mapeo. Points appear in Map Editor again.
Doing a window refresh in the code also seems to fix it, but it has to be after a certain period of time. See the timeout added. 
I spent an hour or so trying to figure out where in iD we could do this directly, instead of hacking it on top. I wouldn't recommend merging this pull request as it is a total hack, but it is better than people thinking they've lost their data entirely. I just haven't figured out a better way quite yet.
> HACK: refresh iD editor to fix bug where points would not appear

- CHANGELOG.md
- README.md
- docs/offline_tiles.md
- index.js
- locales/en.json
- locales/es.json
- package.json
- src/main/menu.js
- src/main/tile-importer.js
- src/main/tile-server.js
- src/main/user-config.js
- src/renderer/components/MapFilter.js
* Map tiles and aerial imagery now must be referenced from under a `styles`  directory. If you were using background imagery in 3.x, you will need to change your URL from `/Offline-Maps/...` to `/styles/Offline-Maps/...`. 
* Presets require a namespace now, which is `default`. If you don't see your presets from a previous installation, you'll need to re-import the configuration file from **File->Import configuration**
> Tiles asar

- package.json
Resolves the minor warning " warn mapeo-desktop@4.0.4-beta license should be a valid SPDX license expression" See https://spdx.org/licenses/ for more description. 
This field is also used  for generating .deb package metadata  #219
> Correcting the invalid SPDX "license" expression

- docs/KNOWN_ISSUES.md
Adding a quick note about mapeo-desktop build failures with Node.js 10 or later
See https://github.com/digidem/mapeo-desktop/issues/228
> Add note about Node.js 10+ build failures

- README.md
I think it is essential for new contributors to export a GH_TOKEN before they do 'npm run dist'.
> Adding GH_TOKEN step to build process.

- package.json
Removing "--arch=x64" hard limit would allow building and running integration tests on windows 32-bit machines. Without this option, the arch setting will be picked from environment.  
Fixes https://github.com/digidem/mapeo-desktop/issues/237
Tested on Windows 7 32-bit machine
> Remove --arch=x64 option

- package.json
Correctly target the latest electron stable release [2.0.18](
https://electronjs.org/releases/stable?version=2#2.0.18) resolves the problem running mapeo-desktop on windows 32-bit systems.  
Fixes https://github.com/digidem/mapeo-desktop/issues/238
> Correct leveldb electron rebuild target to 2.0.18

- docs/offline_tiles.md
In Windows Powershell the output parameters needs to be within double quotes ( " " ). I believe otherwise the curly braces ({}) are interpreted as Unicode escape sequence
> Enclose tile-dl output paramters in double quotes

- .github/workflows/nodejs.yml
- package.json
`electron-builder install-app-deps` does not seem to correctly rebuild deps on Windows, this hopefully fixes it.
The goal of using `electron-rebuild` instead of a manual rebuild command is to avoid errors because `leveldown` isn't always in `node_modules/leveldown` and to avoid errors when changing electron versions.
> fix: Fix builds on Windows

- .github/workflows/nodejs.yml
- README.md
- messages/main/en.json
- messages/main/es.json
- messages/main/fr.json
- messages/main/pt.json
- src/main/menu.js
- src/main/tile-importer.js
On a mac, when you try to import custom tiles, the option for using tar files was not visible in the UI. Since asar compatibility will be [deprecated soon](https://github.com/digidem/mapeo-server/issues/53), this PR removes it from the default menu options.
The tar format will now be the default format for uploading tiles, and this, combined with the [tilserver port change in id-mapeo](https://github.com/digidem/iD-mapeo/pull/9) fixes this issue: https://github.com/digidem/mapeo-desktop/issues/261
cc @gmaclennan @okdistribute
> fix: Remove asar from the import menu

- .github/workflows/nodejs.yml
No idea why rimraf v3 broke this, but pinning to v2 seems to work
> fix: Fix Windows CI/CD for automated builds

- package.json
Fixes https://github.com/digidem/mapeo-desktop/issues/276
This should have been in 5.0.3 but for some reason was missing (https://github.com/digidem/mapeo-desktop/issues/276)
Devices were appearing and disappearing in the sync screen on desktop
Pin [discovery-swarm](https://github.com/mafintosh/discovery-swarm) to v6.0.0 because the error seems to come from an issue in the latest discovery swarm.
> fix: Fix flickering of devices in sync screen

- index.js
- splash.html
- src/main/window-state.js
- static/css/base.css
fixes #283
Tested this on my linux laptop.
This bug was introduced with the new window state manager.
> fix: only one window at a time during startup.

- messages/renderer/en.json
- src/main/i18n.js
- src/main/ipc.js
- src/renderer/app.js
- src/renderer/components/Home.js
- src/renderer/components/MapEditor/index.js
- src/renderer/components/dialogs/ChangeLanguage.js
- ~[ ] My changes have been tested with the [mobile app](https://github.com/digidem/mapeo-mobile/releases).~ N/A
This re-implements the change language dialog in mapeo desktop. fixes #263, #149, #148
> Change language dialog

- .github/workflows/nodejs.yml
- package.json
Windows 32-bit builds will now work, with leveldown@5.6.0.
This raises the size of the Windows build. I wonder if we want to separate the builds into two executables (win32 and x64), which would make them ~75mb each.
Pros: Smaller downloads, faster on sluggish internet.
Cons: Multiple options to decide upon, could download the wrong one if not careful.
-> to mitigate this con, we can update the [download page](https://digital-democracy/mapeo) to automatically find out if you're on 32 or 64 bit machine and suggest the correct one for you.
Should we separate the windows build into 32 and 64 bit versions?
> fix: win32 builds bundled into the windows release

- src/renderer/app.js
- src/renderer/components/Home.js
- src/renderer/components/MapEditor/index.js
- src/renderer/components/dialogs/ChangeLanguage.js
Some small fixes to the language switch dialog:
- Show the currently selected locale
- Allow the user to cancel language switch
Also wrote code to change language without a force-refresh, but our iD Editor integration with React was unhappy (iD re-renders everything when you switch language, and we have a React component patched into the iD toolbar).
> fix: Small fixes to language switcher

- src/renderer/components/MapEditor/index.js
The schema for Mapeo presets and fields differs slightly from iD Editor. This improves the conversion of presets used in Mapeo so that they better appear when viewing monitoring data in the territory view of Mapeo Desktop.
- Fixes fields of type `text` where `appearance=singleline` (was causing crash)
- Uses the iD Editor `semiCombo` type to display select-multiple fields (NB: The resulting field is a semi-colon-separated string, whereas Mapeo expects this to be an array, so this will not work for editing observations in the territory view).
- Uses the correct labels defined in the preset for select fields.
> fix: Improve conversion of Mapeo presets for iD Editor

- package-lock.json
- package.json
- webpack.common.js
- webpack.dev.js
- webpack.prod.js
Currently we are using the development build of react in the packaged
app. The development build is slower, see:
https://reactjs.org/docs/optimizing-performance.html
The fix is a little complicated: Normally you would build a bundle (including React) with `process.env.NODE_ENV = 'production'`. However, we use webpack with `target='electron-renderer'` and this loads all modules as externals e.g. they are required at runtime rather than included in a single bundle. The `webpack.environmentPlugin()` does not set `NODE_ENV` for runtime, it only replaces the variable in moduels included in the bundle (react isn't included, because it is 'external').
The hacky workaround is to patch in `process.env.NODE_ENV = 'production'` to the output bundle from webpack. A better long-term solution might be …
> feat: Use production build of react in packaged app

- .github/workflows/nodejs.yml
- .npmrc
- package-lock.json
- package.json
I noticed that we had an `.npmrc` file that was turning package-lock off, and we were using `npm install` on Github CI which does not strictly follow package-lock.
This PR turns package-lock on, and uses `npm ci` to install things on CI. We should test that the builds from this PR work before merging.
> Chore: use package lock

- package.json
I made some changes to our fork of iD Editor to better display preset fields in iD Editor. The changes are in https://github.com/digidem/iD-mapeo/pull/12 and include:
- Remove support for tagInfo lookups (this only worked for OSM tags, which we do not generally use, and did not work offline.
- Use the UI space for tagInfo for displaying a new field property helperText which shows additional information to help a user answer a question / fill in the field.
- Remove the option to collapse the "All Fields" section of the preset editor. This was unintuitive and could result in users collapsing it by mistake and not being able to find the fields to fill in.
- Allows labels for fields to span multiple lines
- Removes the "Unknown" defult placeholder, and just displays an empty input box if no …
> feat: Support helperText for fields in iD and improve field display

- .storybook/__mocks__/electron-timber.js
- .storybook/__mocks__/node-wifi.js
- .storybook/webpack.config.js
The introduction of `electron-timber` and `node-wifi` packages caused storybook to fail to load.
> fix: React Storybook now runs again

- .eslintrc
- .gitignore
- README.md
- index.js
- messages/main/en.json
- package-lock.json
- package.json
- src/background/index.js
- src/background/mapeo-ipc.js
- src/background/mapeo.js
- src/background/server.js
- src/background/tile-importer.js
- src/logger.js
- src/main/i18n.js
- src/main/ipc.js
- src/main/menu.js
- src/main/user-config.js
- src/renderer/app.js
- src/renderer/components/MapEditor/ExportButton.js
- src/renderer/components/MapFilter/DataExportDialog.js
- src/renderer/components/MapFilter/MapExportDialog.js
- src/renderer/components/MapFilter/MapFilter.js
- src/renderer/components/SyncView/SyncAppBar.js
- src/renderer/components/SyncView/index.js
- src/renderer/create-zip.js
- src/renderer/new-api.js
- src/store.js
Writes files to disk, and improves logging with three levels:
* debug (for developers), printed only to console
* info (good things, infrequent), printed to console and written to disk in %DATE%.log
* errors (bad things, infrequent), printed to console and written to disk in %DATE%.error.log
All processes (background, main, renderer) will write to these files.
This PR also currently reverts back to old behavior for logging during development debugging, where the background process logs in the background window, the frontend JS in the renderer console, and the electron main process in the terminal.
If we want to keep `electron-timber` behavior that will need to be modified. I have not found it to be not essential for my development, as I prefer the Chrome debugger to the terminal, because …
> Better logging, and log files written to disk

- bin/mock.js
- messages/renderer/en.json
- messages/renderer/es.json
- messages/renderer/pt.json
- package-lock.json
- package.json
- src/background/mapeo.js
- src/renderer/components/SyncView/SyncButton.js
- src/renderer/components/SyncView/SyncTarget.js
- src/renderer/components/SyncView/index.js
This fixes underlying sync state bugs by integrating updates from Mapeo Core that were finished in May by @noffle.
This will need to be a coordinated [release with Mapeo Mobile v5 ](https://github.com/digidem/mapeo-mobile/pull/358)
Depends upon https://github.com/digidem/mapeo-core/pull/94
Here's a demo of me trying to break it! 
https://www.dropbox.com/s/udeevnpniw1r7pn/fix-that-sync-bug.mp4?dl=0
Open question to @gmaclennan  -- do we want to abstract this sync state client logic into a `@mapeo/client` module to re-use in mobile? Do we want to do this now or later? Ideally the only difference btwn mobile & desktop is the user interface/presentation layer, not the state logic
> chore(deps): Update @mapeo/core to v8.2.2

- src/renderer/components/SyncView/SyncTarget.js
If a device has an error, it will now still show the device name
> fix: After a sync error, keep the device name visible

- .github/workflows/nodejs.yml
The Github actions config `jobs.build.strategy.matrix.config` had some extra fields that are not needed. This seems to be related to the required checks on each PR. This PR removes config variables in the matrix that are not needed. It shouldn't change anything, just need to check that the artifacts names are correct after the CI runs.
> chore: Remove unnecessary matrix config from github action CD

- .github/workflows/nodejs.yml
This just removes the warning from Github actions because this is not a valid option for actions/setup-node. See also https://github.com/actions/setup-node/pull/42
> chore: Remove un-used architecture option for actions/setup-node

- package.json
Fixes the layout of icons in the DMG installer for MacOS. Was this:
After:
> fix: Fix icon layout in dmg for MacOS

- src/main/i18n.js
- src/main/ipc.js
- [NA] If my changes depend upon an update to a dependency, I have updated the package-lock.json file using `npm install --package-lock`
Mapeo was saving the system locale to the config always on startup, so if you change system languages and reopened Mapeo it wouldn't also change system languages.
This now only persists the change in language if the user explicitly requests to change the language through the User Interface.
> fix: Only save the language to config when changed manually. Fixes #400

- index.js
- package-lock.json
- package.json
You'd get `EPERM` permissions errors if you tried to remove the Mapeo config directory using `rm -rf ~/.config/Mapeo`
> fix: Mapeo config directory should be removable

- package-lock.json
- package.json
- src/renderer/components/MapFilter/ViewWrapper.js
- src/renderer/components/MapFilter/types.js
`mapeo-schema` used to generate flow types from JSON schema. Mapeo Desktop defined more strict types manually. `mapeo-schema@2` includes those manually defined types, and this PR switches Mapeo Desktop to use the types from mapeo-schema.
> chore: move flow types into mapeo-schema

- fixtures/observations.json
- src/renderer/components/MapFilter/ReportView/PDFReport.js
There was a bug with how images wrap across page boundaries in PDF reports. If an image could not completely fit on the page, the image is correctly shown on the next page, but the image border was wrapped across the page, leaving an empty box, see:
This PR fixes wrapping to ensure that the image container (the border) and the image both move onto the next page together.
I also added some extra images to the first observation fixture, and visually checked the fix using `npm run storybook` and viewing the page wrapping before and after to confirm that images wrap correctly.
@jencastrodoesstuff this should fix #433.
> fix: Fix pdf report image wrapping

- messages/renderer/en.json
- src/renderer/components/MapFilter/DataExportDialog.js
- src/renderer/components/MapFilter/MapExportDialog.js
- src/renderer/create-zip.js
It is possible for Mapeo Desktop to be missing originals of images attached to observations. This is not obvious to the user in the app because we always show the preview-sized images (1,200px). This can happen because phone-to-phone sync only syncs thumbnails and previews, not originals, to reduce disk space usage on phones. As a result if a phone has never synced with Desktop, only the previews and thumbnails will be available.
Currently, if the user tries to export observations that link to images with missing originals, via either the Webmaps export, or the data export with "Originals" selected, then the images will be missing from the exported data, with no warning shown to the user …
> fix: Fallback to exporting preview-sized images if originals are missing

- index.js
- src/background/index.js
- src/background/mapeo-core/mapeo.js
- src/logger.js
- src/main/index.js
- src/renderer/components/dialogs/Error.js
~- [ ] My changes have been tested with the [mobile app](https://github.com/digidem/mapeo-mobile/releases).~
When Mapeo Core has a fatal error, it will now give the user at least some indication as to why, which can be then screenshot and sent to us. This error will also be reported to Bugsnag if they are online.
Found this while attempting to debug https://github.com/digidem/mapeo-desktop/issues/440
There will also be a log file generated at `/Mapeo/logs/YEAR-MONTH.error.log` for example, on a Mac in October `/Users/karissa/Library/Application\ Support/Mapeo/logs/2020-10.error.log`
> Fix: Display error to user when it is a fatal mapeo core error

- src/renderer/components/MapFilter/MapExportDialog.js
This is a small change in the `<MapExportDialog>` that removes this warning message in the developer console:
The warning is triggered when an input's value state changes between `undefined` (or `null`) and an actual value. This warning can be removed when "no value" is set to an empty string, instead.
This component is my reference for building the ICCA export dialog, which also makes similar use of controlled input state. I'm writing that component to not throw this warning and wanted to "backport" that change to this component as well. While this warning doesn't ever seem to cause user-facing bugs or performance impacts, cleaning up the console warning helps make the developer …
> fix(MapExportDialog): fix React controlled/uncontrolled state warning

- package-lock.json
- package.json
- src/renderer/components/Home.js
- src/renderer/components/SyncView/SyncAppBar.js
> fix: Fix errors from Wifi Status display and disable on MacOS

- src/renderer/components/MapEditor/ExportButton.js
Closing the export menu via an outside click or the <kbd>esc</kbd> key causes the download dialog to appear. This PR fixes the behavior so that those interactions only close the menu
> fix: do not show download dialog when closing export menu

- builder.config.js
Second thoughts about this: this way will keep the s3 folder better organized and it will be easier to write the re-write rule in https://github.com/digidem/mapeo-releases-worker
> fix: change publish path for win-ia32

- build/app-update.yml
- builder.config.js
- src/main/auto-updater.js
> chore: Autoupdate fixes

- src/renderer/components/MapEditor/index.js
Fixes #503.
This is just as much an experiment in doing open-source contributions to Mapeo code as it is fixing a very small thing discussed today with @gmaclennan - hiding several edit options in Mapeo Territory view that we are deeming to not be very helpful to show to end users.
Please let me know if I did this right in terms of filing an issue, submitting a PR, and versioning (I thought that `fix` was an appropriate prefix considering it's so small, but maybe it's a `feat` since it's not technically a bug?) I'd be happy to work with the team to improve on our guidelines for open-source contributions where helpful and needed 🙂
> fix: Hide tag & relationship editors on Territory sidebar

- src/renderer/components/MapEditor/index.js
This PR hides several options in the iD Background and Map Data panes (Overlays, Display Options, Adjust Imagery Offset, Photo Overlays, and Fill Areas) that are currently not useful to Mapeo users, and in the case of Photo Overlays and Fill Areas, causing bugs to occur. Until we can figure out how these can be useful, we have decided to hide them during Mapeo QA Manual Testing (submitted by @aliya-ryan on September 14, 2021).
In the future, we may want to refactor some of these iD Editor style overrides.
Fixes #523
> hide non-useful iD Background and Map Data options

- src/renderer/components/MapEditor/index.js
This is a small fix for https://github.com/digidem/mapeo-desktop/issues/512.
It looks like Mapeo was inheriting some stylistic properties from iD that resulted in the previously selected layer remaining highlighted with a gray background (just the same as the active layer, which is confusing).
This minor PR adds some internal CSS to override the iD style and resets the background for `.switch` class in the iD background list to none.
> Reset background color for .switch in iD Background list

- index.js
Fixes #527
The default tile server port was changed to `5100` in 5467c19dddadd4d45391b8e9a7df7975d60d3919 :
https://github.com/digidem/mapeo-desktop/blob/5467c19dddadd4d45391b8e9a7df7975d60d3919/index.js#L27
Not entirely sure if that was intentional but for the sake of restoring previously working behavior and avoiding updates to programmatic documentation, this commit restores the default port to `5005`
> fix: Restore default tile server port to 5005

- package-lock.json
- package.json
`flow-geojson` is defined as both a normal dependency and a dev dependency, causing a console warning on dep installation. It only needs to be a dev dependency
> chore: make flow-geojson dev dep only

- src/renderer/components/MapFilter/ReportView/ReportViewContent.js
This changes the default name of the downloaded reports from `Mapeo-Monitoring-Report.pdf` to `Mapeo Observation Report.pdf`
closes #518
> Report Download title

- messages/renderer/en.json
Forgot to run `extract-messages` command when we updated a translatable message [here](https://github.com/digidem/mapeo-desktop/commit/72f9387). In the future, this will be better automated using git hooks (see #534)
> fix: Fix translation entry for default report file name

- src/renderer/components/MapEditor/index.js
Resolves https://github.com/digidem/mapeo-desktop/issues/532
This PR unhides the Overlays submenu in the Background menu, since this menu now provides useful functionality for an end user in the latest version of Mapeo Desktop.
> fix: Reactivate Overlays menu in Background settings

- src/client-ipc.js
Closes #613 
I didn't realize that the Node EventEmitter will throw if you do `emit("error")` but do not handle the error. We currently don't handle errors on the broadcast channel, so for now just logging them. The whole error handling in Mapeo Core / IPC needs a rethink.
> fix: Log instead of emit errors from IPC

- src/renderer/components/MapEditor/index.js
Resolves https://github.com/digidem/mapeo-desktop/issues/620
Forgot to add conventional commits format initially, so rewrote the commit messaging - hence the multiple commits. Will squash when merging upon approval.
> fix: Hide generic geometry presets in territory

- .github/workflows/nodejs.yml
- package-lock.json
- package.json
Fixes #625 (see [builder changelog](https://github.com/electron-userland/electron-builder/releases/tag/v22.11.9))
Tested by successfully installing the associated MacOS `zip` asset generated in [CI](https://github.com/digidem/mapeo-desktop/actions/runs/1491755119)
Notes:
- **Important**: Upgrades the node version used in **development** from 12 to 14, which is required for this dependency upgrade. This **does not** affect the node runtime that's used within Electron itself, which still remains on 12 in this case
> fix: Upgrade electron builder to latest version

- src/renderer/components/MapEditor/index.js
Partial fix for #452 although there are other things to address. 
This PR hides the `Help` button in Mapeo Desktop Territory, since the content of the Help pane that it opens is leftover from iD Editor / OSM and has not at all been customized for Mapeo. It is more confusing than helpful. It also provides a link back to the Walkthrough which is buggy and also not customized for Mapeo.
Trainers from the field report back that they have to tell their users to ignore this pane, which does not inspire confidence. So until we have customized the content, let's hide it for now.
There are still two remaining tasks to fully address disabling this inherited feature, however:
1) The `H` key still …
> fix: hide unhelpful iD Help pane until properly customized for Mapeo

- src/renderer/components/MapEditor/index.js
This PR hides a few more things in iD Editor (Territory) that are not relevant to, or currently useful in, Mapeo:
* A few broken OSM changeset links seen upon saving edits:
* The `Add field` field in Edit feature which does not currently populate from the configuration, and is therefore confusing to our users.
* The `Imagery info / Report a Problem`  link at the bottom of `Background` which pertains to the online Esri / Bing / Mapbox layers brings one to the iD Github; not something our users are likely to know what to do with.
> fix: hiding more superfluous iD Editor content

- package-lock.json
- package.json
- src/renderer/components/MapFilter/MapView/MapView.js
- src/renderer/components/MapFilter/MapView/MapViewContent.js
- src/renderer/components/MapFilter/MapView/ObservationLayer.js
Closes #615 
Notes:
- Supports the use of a `color` field for a preset, which should be any color that's supported by the [CSS3 color spec](https://www.w3.org/TR/css-color-3/)
- Fallback color is the same red color we've been using prior to this change
- We should technically update `mapeo-schema` to reflect this, but considering upcoming work it may not be worth doing for now 
- Adds a new dependency: [validate-color](https://github.com/dreamyguy/validate-color)
---
Preview:
- I added a color field for the following default categories as follows: 
```js
// cave.json
{ 
"color": "invalid-color",
...
}
// threat.json
{ 
"color": "firebrick",
...
}
// river.json
{ 
"color": "#0000cd",
...
}
// streamjson
{ 
"color": "#0cd",
...
}
```
> feat: Support custom colors for displayed observations

- package-lock.json
- package.json
Upgrades `mapeo-settings` to v2.1.3 which includes a fix to prevent a default value for settings metadata from being set at the dep level. See https://github.com/digidem/mapeo-settings/pull/7 for more context
> fix: Properly use fallback settings metadata when user-defined one is missing

- .github/workflows/nodejs.yml
Currently CI will break if run on a PR from a fork. This is because
the secrets are passed as empty strings, and electron-builder sees this
as "not null" so still tries to sign the installers.
This change ensures that the environment variables are not set when
the Github action is triggered from a forked repo, so that electron
builder just builds an un-signed installer.
We will not be able to fully test this here. We can ensure that the normal path still runs - e.g. generating signed installers from internal PRs - but we will need to merge and then PR from a fork to check this actually fixes things.
> chore: fix CI builds when run from a forked repo

- package-lock.json
- package.json
Should only change the Mapeo for ICCAs release - this is not included in the general Mapeo release.
> chore: bump mapeo-config-icca@1.6.0

- src/renderer/components/MapEditor/index.js
Presets with translations in multiple languages (e.g. the default config presets that we ship with Mapeo) were only showing up in English in the Territory view, ignoring the selected locale of Mapeo.
**Before:**
The default presets are already translated. This PR fixes a bug in the code that added the translations to iD Editor.
**After:**
> fix: fix translations of presets in territory view
